name: ai_project
description: "an AI Assistant (chatbot, Image Generator and Language Translator) app based on ChatGPT developed by Bhushan Waghode. )"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  icons_launcher: ^2.1.7
  lottie: ^3.1.2
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0
  translator_plus: ^1.0.1
  get: ^4.6.6
  google_generative_ai: ^0.4.3
  intl: ^0.19.0
  flutter_animate: ^4.5.0
  bloc:
  flutter_bloc:
  dio:
  translator: ^1.0.0
  provider: ^6.1.2
  animated_text_kit: ^4.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lottie/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
